/**
 * 📁 INSTITUTION FILE SERVICE
 *
 * Servicio para manejar la lectura y escritura del archivo institutionDetector.ts
 * en el entorno de desarrollo local.
 */

import { InstitutionInfo } from '@/utils/institutionDetector';

interface FileServiceResult {
  success: boolean;
  message: string;
  data?: any;
}

export class InstitutionFileService {
  private static readonly FILE_PATH = './src/utils/institutionDetector.ts';

  /**
   * Simula la lectura del archivo actual
   */
  static async readCurrentFile(): Promise<FileServiceResult> {
    try {
      // En desarrollo local, esto usaría fs para leer el archivo real
      // Por ahora simulamos la respuesta

      return {
        success: true,
        message: 'Archivo leído correctamente',
        data: 'Contenido del archivo simulado'
      };
    } catch (error) {
      return {
        success: false,
        message: 'Error al leer el archivo de instituciones'
      };
    }
  }

  /**
   * Genera el código TypeScript para el archivo institutionDetector.ts
   */
  static generateInstitutionCode(institutions: InstitutionInfo[]): string {
    const timestamp = new Date().toISOString();

    return `export interface InstitutionInfo {
  id: string;
  name: string;
  displayName: string;
  credentialMessage: string;
  keywords: string[];
  variants: string[];
  color: {
    bg: string;
    text: string;
    border: string;
  };
  icon: string;
}

export interface DetectionResult {
  isInstitution: boolean;
  institution?: InstitutionInfo;
  matchedTerm?: string;
  confidence: number; // 0-100
}

// 🤖 Auto-generated by Institution Manager on ${timestamp}
// ⚠️  DO NOT EDIT MANUALLY - Changes will be overwritten
const INSTITUTIONS: InstitutionInfo[] = [
${institutions.map(inst => `  {
    id: '${inst.id}',
    name: '${inst.name}',
    displayName: '${inst.displayName}',
    credentialMessage: '${inst.credentialMessage.replace(/'/g, "\\'")}',
    keywords: ${JSON.stringify(inst.keywords)},
    variants: ${JSON.stringify(inst.variants)},
    color: {
      bg: '${inst.color.bg}',
      text: '${inst.color.text}',
      border: '${inst.color.border}'
    },
    icon: '${inst.icon}'
  }`).join(',\n')}
];

/**
 * Normaliza texto para comparación: minúsculas, sin acentos, sin espacios extras
 */
const normalizeText = (text: string): string => {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\\u0300-\\u036f]/g, '') // Quitar acentos
    .replace(/[^\\w\\s]/g, ' ') // Reemplazar símbolos por espacios
    .replace(/\\s+/g, ' ') // Espacios múltiples a uno solo
    .trim();
};

/**
 * Calcula similitud entre dos strings usando algoritmo simple
 * Retorna valor entre 0-100
 */
const calculateSimilarity = (str1: string, str2: string): number => {
  const s1 = normalizeText(str1);
  const s2 = normalizeText(str2);

  if (s1 === s2) return 100;
  if (s1.includes(s2) || s2.includes(s1)) return 85;

  // Algoritmo de distancia de Levenshtein simplificado
  const len1 = s1.length;
  const len2 = s2.length;
  const maxLen = Math.max(len1, len2);

  if (maxLen === 0) return 100;

  let matches = 0;
  const minLen = Math.min(len1, len2);

  for (let i = 0; i < minLen; i++) {
    if (s1[i] === s2[i]) matches++;
  }

  return Math.round((matches / maxLen) * 100);
};

/**
 * Detecta si un término de búsqueda corresponde a una institución
 * @param searchTerm Término ingresado por el usuario
 * @param minConfidence Confianza mínima requerida (default: 70)
 * @returns Resultado de la detección
 */
export const detectInstitution = (
  searchTerm: string,
  minConfidence: number = 70
): DetectionResult => {
  if (!searchTerm || searchTerm.trim().length < 3) {
    return { isInstitution: false, confidence: 0 };
  }

  const normalizedSearch = normalizeText(searchTerm);
  let bestMatch: DetectionResult = { isInstitution: false, confidence: 0 };

  for (const institution of INSTITUTIONS) {
    // Buscar en variantes exactas primero
    for (const variant of institution.variants) {
      const similarity = calculateSimilarity(normalizedSearch, variant);

      if (similarity >= minConfidence && similarity > bestMatch.confidence) {
        bestMatch = {
          isInstitution: true,
          institution,
          matchedTerm: variant,
          confidence: similarity
        };
      }
    }

    // Buscar en keywords también
    for (const keyword of institution.keywords) {
      if (normalizedSearch.includes(normalizeText(keyword))) {
        const similarity = 90; // High confidence for keyword matches

        if (similarity > bestMatch.confidence) {
          bestMatch = {
            isInstitution: true,
            institution,
            matchedTerm: keyword,
            confidence: similarity
          };
        }
      }
    }
  }

  return bestMatch;
};

/**
 * Función auxiliar para agregar nuevas instituciones (para futuro)
 * @param newInstitution Nueva institución a agregar
 */
export const addInstitution = (newInstitution: InstitutionInfo): void => {
  // Validar que no exista ya
  const exists = INSTITUTIONS.find(inst => inst.id === newInstitution.id);
  if (!exists) {
    INSTITUTIONS.push(newInstitution);
  }
};

/**
 * Obtener todas las instituciones configuradas
 */
export const getAllInstitutions = (): InstitutionInfo[] => {
  return [...INSTITUTIONS];
};

/**
 * Buscar institución por ID
 */
export const getInstitutionById = (id: string): InstitutionInfo | undefined => {
  return INSTITUTIONS.find(inst => inst.id === id);
};

/**
 * Función de prueba/debug para validar detecciones
 */
export const testDetection = (): void => {
  const testCases = [
    'carabineros', 'caravineros', 'policia uniformada',
    'pdi', 'policia investigaciones', 'investigaciones',
    'colegio medico', 'colegiomedico', 'medicos',
    'caja araucana', 'caja la araucana', 'compensacion araucana',
    'usuario normal', 'juan perez', '12345678-9'
  ];

  // console.log('🧪 Pruebas de detección de instituciones:');
  testCases.forEach(term => {
    const result = detectInstitution(term);
    // console.log(\`"\${term}" →\`, result.isInstitution ?
      \`✅ \${result.institution?.name} (\${result.confidence}%)\` :
      \`❌ No detectado\`
    );
  });
};`;
  }

  /**
   * Simula escribir el archivo con las nuevas instituciones
   */
  static async writeInstitutionsFile(institutions: InstitutionInfo[]): Promise<FileServiceResult> {
    try {
      const newContent = this.generateInstitutionCode(institutions);

      // console.log('💾 Simulando escritura de archivo...');
      // console.log('📄 Nuevo contenido generado:');
      // console.log(newContent);

      // En un entorno real, aquí se escribiría el archivo:
      // await fs.writeFile(this.FILE_PATH, newContent, 'utf-8');

      // Simular delay de escritura
      await new Promise(resolve => setTimeout(resolve, 800));

      return {
        success: true,
        message: `Archivo actualizado con ${institutions.length} instituciones`
      };
    } catch (error) {
      // console.error('Error writing institution file:', error);
      return {
        success: false,
        message: 'Error al escribir el archivo de instituciones'
      };
    }
  }

  /**
   * Valida que las instituciones tengan la estructura correcta
   */
  static validateInstitutions(institutions: InstitutionInfo[]): { isValid: boolean; errors: string[] } {
    const errors: string[] = [];

    institutions.forEach((inst, index) => {
      if (!inst.id || typeof inst.id !== 'string') {
        errors.push(`Institución ${index + 1}: ID es requerido`);
      }

      if (!inst.name || typeof inst.name !== 'string') {
        errors.push(`Institución ${index + 1}: Nombre es requerido`);
      }

      if (!inst.displayName || typeof inst.displayName !== 'string') {
        errors.push(`Institución ${index + 1}: Nombre para mostrar es requerido`);
      }

      if (!inst.credentialMessage || typeof inst.credentialMessage !== 'string') {
        errors.push(`Institución ${index + 1}: Mensaje de credencial es requerido`);
      }

      if (!Array.isArray(inst.keywords) || inst.keywords.length === 0) {
        errors.push(`Institución ${index + 1}: Keywords son requeridas`);
      }

      if (!Array.isArray(inst.variants) || inst.variants.length === 0) {
        errors.push(`Institución ${index + 1}: Variantes son requeridas`);
      }

      if (!inst.color || !inst.color.bg || !inst.color.text || !inst.color.border) {
        errors.push(`Institución ${index + 1}: Configuración de color incompleta`);
      }

      if (!inst.icon || typeof inst.icon !== 'string') {
        errors.push(`Institución ${index + 1}: Icono es requerido`);
      }

      // Validar IDs únicos
      const duplicateId = institutions.find((other, otherIndex) =>
        otherIndex !== index && other.id === inst.id
      );
      if (duplicateId) {
        errors.push(`ID duplicado encontrado: ${inst.id}`);
      }
    });

    return {
      isValid: errors.length === 0,
      errors
    };
  }

  /**
   * Crea una copia de respaldo del archivo antes de modificarlo
   */
  static async createBackup(): Promise<FileServiceResult> {
    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const backupPath = `./src/utils/institutionDetector.backup.${timestamp}.ts`;

      // console.log(`📋 Creando respaldo en: ${backupPath}`);

      // En un entorno real:
      // await fs.copyFile(this.FILE_PATH, backupPath);

      return {
        success: true,
        message: `Respaldo creado: ${backupPath}`
      };
    } catch (error) {
      // console.error('Error creating backup:', error);
      return {
        success: false,
        message: 'Error al crear respaldo del archivo'
      };
    }
  }

  /**
   * Implementa la funcionalidad completa de guardado seguro
   */
  static async saveInstitutionsSafely(institutions: InstitutionInfo[]): Promise<FileServiceResult> {
    try {
      // 1. Validar datos
      const validation = this.validateInstitutions(institutions);
      if (!validation.isValid) {
        return {
          success: false,
          message: `Errores de validación: ${validation.errors.join(', ')}`
        };
      }

      // 2. Crear respaldo
      const backupResult = await this.createBackup();
      if (!backupResult.success) {
        // console.warn('Advertencia: No se pudo crear respaldo');
      }

      // 3. Escribir archivo
      const writeResult = await this.writeInstitutionsFile(institutions);

      if (writeResult.success) {
        // console.log('✅ Instituciones guardadas correctamente');
        // console.log('🔄 Recarga la aplicación para ver los cambios');
      }

      return writeResult;
    } catch (error) {
      // console.error('Error in saveInstitutionsSafely:', error);
      return {
        success: false,
        message: 'Error inesperado al guardar instituciones'
      };
    }
  }
}

export default InstitutionFileService;