// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shakktuvnlioyxtzcjdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoYWtrdHV2bmxpb3l4dHpjamRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mjc2MjksImV4cCI6MjA2NTUwMzYyOX0.GHp908Cr41y3bl7BYaH5_SH6oHk4v1Pyy_FDw40308U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);